"""
Module 3: 1D Physics-Based Restoration (Richardson-Lucy & BID)
=============================================================
A 1-Dimensional Richardson-Lucy deconvolution algorithm designed to 
enhance the resolution of ONT nanopore signals that have flattened or 
merged due to bandwidth limits in homopolymer regions.

Author: FizyGame
Date: 2026
"""

from __future__ import annotations

import logging

import numpy as np
from scipy.signal import fftconvolve

logger = logging.getLogger("rl_deconvolution")

def gaussian_psf_1d(size: int, sigma: float) -> np.ndarray:
    """
    Creates a 1-dimensional Gaussian Point Spread Function (PSF).
    
    Args:
        size (int): Filter size (odd sizes are ideal for convolution centering).
        sigma (float): Standard deviation (spread width) of the Gaussian window.
        
    Returns:
        np.ndarray: 1D Gaussian filter normalized so its sum is 1.
        
    Example:
        >>> psf = gaussian_psf_1d(11, 2.0)
        >>> assert np.isclose(psf.sum(), 1.0)
    """
    assert size > 0, "PSF size must be greater than 0."
    assert sigma > 0, "Sigma must be greater than 0."
    
    # Create 0-centered x axis
    # e.g., size=5 -> [-2, -1, 0, 1, 2]
    x = np.arange(-size // 2 + 1 if size % 2 == 0 else -(size // 2), size // 2 + 1)
    
    psf = np.exp(-(x ** 2) / (2 * sigma ** 2))
    
    # L1 normalization (Energy conservation for the signal)
    psf /= psf.sum()
    
    return psf

def shift_to_positive(
    signal: np.ndarray, 
    offset: float = 1e-6, 
    method: str = "min_shift"
) -> tuple[np.ndarray, dict]:
    """
    Transforms the signal into a strictly positive space required for 
    Richardson-Lucy deconvolution. The RL algorithm mathematically cannot 
    operate with negative values.
    
    Args:
        signal (np.ndarray): Original signal (which may contain negative values).
        offset (float): Buffer value added to prevent multiplication/division by zero.
        method (str): Transformation method ("min_shift" or "minmax").
        
    Returns:
        tuple[np.ndarray, dict]: 
            - The signal shifted to positive space.
            - A dictionary containing parameters required for the inverse shift.
            
    Raises:
        ValueError: If an unknown method is provided.
    """
    signal = np.asarray(signal, dtype=np.float64)
    params = {"method": method, "offset": offset}
    
    if method == "min_shift":
        sig_min = signal.min()
        shift_val = abs(sig_min) + offset if sig_min <= 0 else 0.0
        pos_signal = signal + shift_val
        params["shift_val"] = shift_val
        
    elif method == "minmax":
        sig_min = signal.min()
        sig_max = signal.max()
        ptp = sig_max - sig_min
        if ptp < 1e-12:
            ptp = 1.0
        pos_signal = (signal - sig_min) / ptp + offset
        params["min"] = sig_min
        params["ptp"] = ptp
        
    else:
        raise ValueError(f"Invalid method: {method}. Use 'min_shift' or 'minmax'.")
        
    return pos_signal, params

def inverse_shift(signal: np.ndarray, params: dict) -> np.ndarray:
    """
    Restores the signal mapping generated by `shift_to_positive` 
    back to its original amplitude space.
    
    Args:
        signal (np.ndarray): Processed, strictly positive signal.
        params (dict): The parameter dictionary returned by `shift_to_positive`.
        
    Returns:
        np.ndarray: Signal mapped back to its true physical space.
    """
    method = params.get("method")
    offset = params.get("offset", 0.0)
    
    if method == "min_shift":
        shift_val = params["shift_val"]
        return signal - shift_val
        
    elif method == "minmax":
        sig_min = params["min"]
        ptp = params["ptp"]
        return (signal - offset) * ptp + sig_min
        
    else:
        raise ValueError(f"Invalid transformation method parameter: {method}")

def richardson_lucy_1d(
    signal: np.ndarray,
    psf: np.ndarray,
    iterations: int = 50,
    epsilon: float = 1e-12
) -> np.ndarray:
    """
    Vectorized Richardson-Lucy (RL) Deconvolution for 1D signals.
    
    Iterative formula:
        I_{k+1} = I_k * conv(PSF_flipped, I_o / (conv(I_k, PSF) + eps))
        
    (Assuming a symmetric Gaussian PSF, PSF_flipped = PSF).
    
    Note: The input signal must be strictly positive. 
    Otherwise, `shift_to_positive` should be used beforehand.
    
    Args:
        signal (np.ndarray): Positive 1D observation signal (I_o).
        psf (np.ndarray): 1D Point Spread Function.
        iterations (int): Maximum RL loop iterations.
        epsilon (float): Small parameter to isolate division-by-zero errors.
        
    Returns:
        np.ndarray: The resolution-enhanced (deconvolved) 1D signal (I_k).
        
    Raises:
        ValueError: If the signal contains negative or zero values.
    """
    signal = np.asarray(signal, dtype=np.float64)
    psf = np.asarray(psf, dtype=np.float64)
    
    if np.any(signal < 0):
        raise ValueError(
            "The Richardson-Lucy algorithm cannot handle negative inputs "
            "as it causes undefined mathematical errors. "
            "Use shift_to_positive() first."
        )
        
    # Initial estimate for the iteration (usually the observation itself)
    estimate = signal.copy()
    
    # We assume a symmetric PSF is used.
    # If it were asymmetric: psf_flipped = psf[::-1]
    psf_flipped = psf[::-1]
    
    # Vectorized RL Iteration Loop
    for _ in range(iterations):
        # 1. System response of the estimated signal
        # mode='same' ensures output has the same size as input
        conv_est = fftconvolve(estimate, psf, mode='same')
        
        # 2. Ratio: Actual observation / Estimated observation
        # Epsilon prevents division-by-zero errors
        ratio = signal / (conv_est + epsilon)
        
        # 3. Error back-projection
        error_proj = fftconvolve(ratio, psf_flipped, mode='same')
        
        # 4. Multiplicative Update Rule
        estimate *= error_proj
        
        # Physical constraint: Radiance/Current must be positive
        # Protect against underflow producing very small numbers
        estimate = np.clip(estimate, epsilon, None)
        
    return estimate

# CLI Demo
if __name__ == "__main__":
    import matplotlib.pyplot as plt
    
    # 1. Generate Target Signal (Sharp peaks - ideal homopolymer transitions)
    np.random.seed(42)
    x = np.arange(200)
    true_signal = np.zeros_like(x, dtype=float)
    true_signal[40:50] = 50.0  # Sharp step
    true_signal[120:125] = 40.0 # Shorter sharp step
    
    # 2. Blurring factor (simulating ONT Sensor/Pore bandwidth limitation)
    psf = gaussian_psf_1d(size=15, sigma=3.0)
    
    # 3. Generate blurred signal
    blurred_signal = fftconvolve(true_signal, psf, mode='same')
    noisy_blurred = blurred_signal + np.random.normal(0, 1.0, len(x))
    
    # 4. Richardson-Lucy Restoration
    # First, move to positive space (noise may cross zero)
    pos_noisy, params = shift_to_positive(noisy_blurred, method="min_shift")
    
    # RL iteration
    restored_pos = richardson_lucy_1d(pos_noisy, psf, iterations=40)
    
    # Restore to original space
    restored = inverse_shift(restored_pos, params)
    
    plt.figure(figsize=(10, 5))
    plt.plot(x, true_signal, 'k--', label="Original Sharp (Unknown)", alpha=0.6)
    plt.plot(x, noisy_blurred, 'r-', label="ONT Blurred + Noise", alpha=0.7)
    plt.plot(x, restored, 'g-', label="RL Deconvolution (Restored)", linewidth=2)
    plt.title("Richardson-Lucy 1D Deconvolution Demo")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()
